Move ecephys align timestamps
AllenInstitute/ecephys_etl_pipelines pull request #16
Opened 2021-06-23 16:08 UTC by njmei

This PR is meant to encapsulate commits related to migrating ecephys `align_timestamps` functionality from AllenSDK to ecephys_etl_pipelines.

2021-06-23 16:31 UTC, djkapner commented on README.md
> +python -m allensdk.brain_observatory.ecephys.align_timestamps --input_json <path to input json> --output_json <path to output json>
example will be out-of-date

2021-06-23 16:32 UTC, djkapner commented on README.md
> +Each mappable file for each probe is aligned and written out. Additionally, the transform is written into the output json.
i know just a copy, and there is a schema, but, this isn't much information here.

2021-06-23 16:33 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +from allensdk.brain_observatory.argschema_utilities import \
now would be a great time to sever the dependency on `argschema_utilities`

2021-06-23 16:34 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +from .barcode_sync_dataset import BarcodeSyncDataset
I think we've stopped using relative imports, because it was causing trouble when some dev was using windows and some particular IDE.

2021-06-23 16:35 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +def align_timestamps(args):
no type hints, no docstring
passing in untyped `dict` is not very explicit, we should try to improve this.

2021-06-23 16:36 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +        print(probe["name"])
no print

2021-06-23 16:36 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +        this_probe_output_info = {}
`= dict()`

2021-06-23 16:37 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +        print("Split times:")
no prints

2021-06-23 16:38 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +def align_timestamps(args):
would probably be easier to test/read/doc to split some of these operations into smaller methods

2021-06-23 16:39 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    input_path = String(
should be `InputFile` type

2021-06-23 16:39 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    output_path = String(
should be `OutputFile` type

2021-06-23 16:42 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +        help="Output path for the mapped version of this file. Will write a 1D timestamps array with values in seconds on the master clock.",
I think these `help`s should be `description`s:
https://github.com/AllenInstitute/argschema/blob/c7cf8fb53166fecd1d1b8f562e5b8c0c12f03a03/argschema/utils.py#L237-L260

2021-06-23 16:44 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +class InputParameters(ArgSchema):
more specific name will make searching on github easier as this repo grows.

2021-06-23 16:45 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +class InputParameters(ArgSchema):
consider specifying default `INFO` for `log_level` as an override.

2021-06-23 16:45 UTC, danielsf requested changes
I didn't look closely at the tests, since they aren't expected to pass anyway.

I got the sense that this is a "copy-and-paste from SDK" ticket. If so, some of my comments may be out of scope. That being said, I think we should at least try to remove that dependence on `allensdk.argschema_utilities` before merging.

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +from allensdk.brain_observatory.argschema_utilities import \
Is there any way we can get away from using `argschema_utilities`? I'm not a huge fan of having our ETL packages depend on the SDK. I also don't like the idea of having a way to handle arguments/schemas outside of unmodified `argschema`.

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/__main__.py
> +def align_timestamps(args):
Can you please add a docstring explaining what this method is meant to do?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +        help='What kind of mappable data is this? e.g. "spike_timestamps"',
Can we specify a finite list of valid values here? See

https://github.com/AllenInstitute/ophys_etl_pipelines/blob/staging/segmentation_dev/src/ophys_etl/modules/segmentation/modules/schemas.py#L88-L89

for an example

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    input_path = String(
Should this be an `argschema.fields.InputFile`?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    output_path = String(
Should this be an `argschema.fields.OutputFile`?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    name = String(required=True, help="Identifier for this probe")
Please add a hint (or, better yet, a validation step) indicating what values are acceptable.

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    barcode_channel_states_path = String(
Should be an `argschema.fields.InputFile`

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    barcode_timestamps_path = String(
Should be an `argschema.fields.InputFile`

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    sync_h5_path = String(
Should be an `argschema.fields.InputFile`

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +    name = String(required=True, help="Identifier for this probe")
Please specify valid values (if possible)

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +def extract_barcodes_from_times(
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +            np.where(
Do you need the `np.where`? Can you just use a boolean mask to select the correct indices?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +            np.where(
Same comment as above, may not need the `np.where`

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +def find_matching_index(master_barcodes, probe_barcodes, alignment_type="start"):
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +    else:
Should this be `elif alignment_type == "end":` followed by an `else` block that raises an exception if an alignment type other than `"start"` or `"end"` is passed in?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +            master_barcodes == probe_barcodes[probe_barcode_index]
Probably don't need the `np.where` here, either

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +def match_barcodes(master_times, master_barcodes, probe_times, probe_barcodes):
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +    # print(master_barcodes)
Remove commented out code

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +def linear_transform_from_intervals(master, probe):
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +        If > 0, the probe clock started before the master clock. If > 0, after.
`translation` can come back `None`. What would that mean?

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/barcode.py
> +def get_probe_time_offset(
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/channel_states.py
> +    **barcode_kwargs :
Where are these additional parameters defined? All of this passing around of `**barcode_kwargs` makes me uneasy. Is there no way to explicitly define the expected arguments (or have some kind of parameter container class that can carry them around?)

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/probe_synchronizer.py
> +    def __init__(
Please include type hinting in the call signature

2021-06-23 16:45 UTC, danielsf commented on src/ecephys_etl/modules/align_timestamps/probe_synchronizer.py
> +        ok_barcodes = np.where((times_array > min_time) * (times_array < max_time))[0]
Can you make this an `np.logical_and`? Multiplying arrays of booleans seems unnecessarily convoluted.

2021-06-23 16:45 UTC, danielsf commented on tests/modules/align_timestamps/test_align_timestamps_module.py
> +    os.path.join("/", "allen", "aibs", "informatics", "module_test_data", "ecephys"),
I assume we are leaving the question of "how do we make this test not depend on Isilon" for a future ticket?

2021-06-23 16:48 UTC, djkapner submitted a review, later dismissed
rubber stamp in anticipation of #17

2021-06-23 20:30 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/_schemas.py
> +class OutputParameters(OutputSchema):
not sure why this needs a base class and then a subclass.

2021-06-23 20:32 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/barcode_sync_dataset.py
> +from allensdk.brain_observatory.ecephys.file_io.ecephys_sync_dataset import (
presumably this will migrate over as well

2021-06-23 20:33 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/barcode_sync_dataset.py
> +    def extract_barcodes(self, **barcode_kwargs):
want explicit args/kwargs

2021-06-23 20:33 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/barcode_sync_dataset.py
> +    def get_barcode_table(self, **barcode_kwargs):
want explicit args/kwargs

2021-06-23 20:34 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/probe_synchronizer.py
> +            print("Num barcodes: " + str(len(barcodes_to_align)))
no print

2021-06-23 20:34 UTC, djkapner commented on src/ecephys_etl/modules/align_timestamps/probe_synchronizer.py
> +            print("Not enough barcodes...setting sampling rate to 0")
no print

2021-06-23 20:36 UTC, djkapner commented on tests/modules/align_timestamps/test_align_timestamps_module.py
> +    executable = ["python", "-m", "allensdk.brain_observatory.ecephys.align_timestamps"]
yikes

2021-07-02 16:13 UTC, danielsf approved these changes

2021-07-02 16:14 UTC, merged